return {[1000974] = {
		unidentifiedDisplayName = "Guillotine Cross Stone (Upper)",
		unidentifiedResourceName = "¿µÈ¥ÀÇÁ¶°¢",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Guillotine Cross Stone (Upper)",
		identifiedResourceName = "¿µÈ¥ÀÇÁ¶°¢",
		identifiedDescriptionName = {
			"A stone that awakens the potential of Guillotine Crosses.",
			"Gives the following effects when compounded on a slot of an Costume Upper Headgear.",
			"_______________________",
			"Reduces global cool time by 1% per 2 levels of ^009900New Poison Research^000000 user learned.",
			"_______________________",
			"When equipped with Guillotine Cross Stone (Garment),",
			"increases ^009900Cross Ripper Slasher^000000 damage by 15%.",
			"When equipped with Guillotine Cross Stone II (Garment),",
			"increases ^009900Counter Slash^000000 damage by 15%.",
			"_______________________",
			"<NAVI>[Aver De Dosh]<INFO>mal_in01,23,113,0,100,0,0</INFO></NAVI>",
			"_______________________",
			"^0000CCWeight:^000000 10"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
		},
		[1000975] = {
		unidentifiedDisplayName = "Guillotine Cross Stone (Middle)",
		unidentifiedResourceName = "¿µÈ¥ÀÇÁ¶°¢",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Guillotine Cross Stone (Middle)",
		identifiedResourceName = "¿µÈ¥ÀÇÁ¶°¢",
		identifiedDescriptionName = {
			"A stone that awakens the potential of Guillotine Crosses.",
			"Gives the following effects when compounded on a slot of an Costume Middle Headgear.",
			"_______________________",
			"Increases melee physical damage by 2% per each level of ^009900Dark Illusion^000000 user learned.",
			"_______________________",
			"When equipped with Guillotine Cross Stone (Garment),",
			"increases ^009900Rolling Cutter^000000 damage by 15%.",
			"When equipped with Guillotine Cross Stone II (Garment),",
			"increases ^009900Cross Impact^000000 damage by 15%.",
			"_______________________",
			"<NAVI>[Aver De Dosh]<INFO>mal_in01,23,113,0,100,0,0</INFO></NAVI>",
			"_______________________",
			"^0000CCWeight:^000000 10"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
		},
		[1000976] = {
		unidentifiedDisplayName = "Guillotine Cross Stone (Lower)",
		unidentifiedResourceName = "¿µÈ¥ÀÇÁ¶°¢",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Guillotine Cross Stone (Lower)",
		identifiedResourceName = "¿µÈ¥ÀÇÁ¶°¢",
		identifiedDescriptionName = {
			"A stone that awakens the potential of Guillotine Crosses.",
			"Gives the following effects when compounded on a slot of an Costume Lower Headgear.",
			"_______________________",
			"Increases long ranged physical damage by 2% per each level of ^009900Cross Ripper Slasher^000000 user learned.",
			"_______________________",
			"When equipped with Guillotine Cross Stone (Garment),",
			"increases ^009900Cross Ripper Slasher^000000 damage by 15%",
			"When equipped with Guillotine Cross Stone II (Garment),",
			"increases physical damage against all race monsters (except players) by 15%",
			"_______________________",
			"<NAVI>[Aver De Dosh]<INFO>mal_in01,23,113,0,100,0,0</INFO></NAVI>",
			"_______________________",
			"^0000CCWeight:^000000 10"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
		},
		[311433] = {
		unidentifiedDisplayName = "Guillotine Cross Stone (Upper)",
		unidentifiedResourceName = "µµµÏÇÇ±Ô¾î",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Guillotine Cross Stone (Upper)",
		identifiedResourceName = "µµµÏÇÇ±Ô¾î",
		identifiedDescriptionName = {
			"A stone that awakens the potential of Guillotine Crosses.",
			"Gives the following effects when compounded on a slot of an Costume Upper Headgear.",
			"_______________________",
			"Reduces global cool time by 1% per 2 levels of ^009900New Poison Research^000000 user learned.",
			"_______________________",
			"When equipped with Guillotine Cross Stone (Garment),",
			"increases ^009900Cross Ripper Slasher^000000 damage by 15%.",
			"When equipped with Guillotine Cross Stone II (Garment),",
			"increases ^009900Counter Slash^000000 damage by 15%.",
			"_______________________",
			"<NAVI>[Aver De Dosh]<INFO>mal_in01,23,113,0,100,0,0</INFO></NAVI>",
			"_______________________",
			"^0000CCWeight:^000000 10"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
		},
		[311434] = {
		unidentifiedDisplayName = "Guillotine Cross Stone (Middle)",
		unidentifiedResourceName = "µµµÏÇÇ±Ô¾î",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Guillotine Cross Stone (Middle)",
		identifiedResourceName = "µµµÏÇÇ±Ô¾î",
		identifiedDescriptionName = {
			"A stone that awakens the potential of Guillotine Crosses.",
			"Gives the following effects when compounded on a slot of an Costume Middle Headgear.",
			"_______________________",
			"Increases melee physical damage by 2% per each level of ^009900Dark Illusion^000000 user learned.",
			"_______________________",
			"When equipped with Guillotine Cross Stone (Garment),",
			"increases ^009900Rolling Cutter^000000 damage by 15%.",
			"When equipped with Guillotine Cross Stone II (Garment),",
			"increases ^009900Cross Impact^000000 damage by 15%.",
			"_______________________",
			"<NAVI>[Aver De Dosh]<INFO>mal_in01,23,113,0,100,0,0</INFO></NAVI>",
			"_______________________",
			"^0000CCWeight:^000000 10"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
		},
		[311435] = {
		unidentifiedDisplayName = "Guillotine Cross Stone (Lower)",
		unidentifiedResourceName = "µµµÏÇÇ±Ô¾î",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Guillotine Cross Stone (Lower)",
		identifiedResourceName = "µµµÏÇÇ±Ô¾î",
		identifiedDescriptionName = {
			"A stone that awakens the potential of Guillotine Crosses.",
			"Gives the following effects when compounded on a slot of an Costume Lower Headgear.",
			"_______________________",
			"Increases long ranged physical damage by 2% per each level of ^009900Cross Ripper Slasher^000000 user learned.",
			"_______________________",
			"When equipped with Guillotine Cross Stone (Garment),",
			"increases ^009900Cross Ripper Slasher^000000 damage by 15%",
			"When equipped with Guillotine Cross Stone II (Garment),",
			"increases physical damage against all race monsters (except players) by 15%",
			"_______________________",
			"<NAVI>[Aver De Dosh]<INFO>mal_in01,23,113,0,100,0,0</INFO></NAVI>",
			"_______________________",
			"^0000CCWeight:^000000 10"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
		},
		[480084] = {
		unidentifiedDisplayName = "Unidentified Garment",
		unidentifiedResourceName = "ÈÄµå",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Fafnir Breath",
		identifiedResourceName = "FAFNIR_MANTEAU",
		identifiedDescriptionName = {
			"A cloak made from Fafnir scales defeated by the hero Sigurd.",
			"_______________________",
			"Reduce incoming damage from fire and water element attacks by 10%.",
			"Reduce incoming damage from players by 5%",
			"Reduce delay after attack by 3%.",
			"_______________________",
			"When refined to 9 or higher,",
			"reduce incoming damage from fire and water",
			"element attacks by additional 20%.",
			"Increase ranged damage dealt to all enemies by 10%",
			"Reduce delay after attack by 5%.",
			"_______________________",
			"When refined to 11 or higher,",
			"reduce incoming damage from fire and water",
			"element attacks by additional 20%.",
			"Increase ranged damage dealt to all enemies by 10%",
			"Reduce delay after attack by 7%.",
			"_______________________",
			"When Dragon Training skill Lv5, MaxHP + 20%, MaxSP + 20%",
			"When Dragon Breath - Water Lv10, can use Deluge Lv5.",
			"_______________________",
			"Increase damage of Dragon's Breath by 20% per 1",
			"Dragon Howling learned, increase Dragon Breath - Water damage by 20%",
			"When Dragon Breath Lv10, can use Volcano Lv5.",
			"_______________________",
			"^0000CCType:^000000 Garment",
			"^0000CCDefense:^000000 12",
			"^0000CCWeight:^000000 10",
			"^0000CCArmor Level:^000000 1",
			"_______________________",
			"^0000CCRequirement:^000000",
			"Base Level 100",
			"All Jobs"
		},
		slotCount = 1,
		ClassNum = 0,
		costume = false
		},
		[1000610] = {
		unidentifiedDisplayName = "Rune Knight Stone (Upper)",
		unidentifiedResourceName = "¿µÈ¥ÀÇÁ¶°¢",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Rune Knight Stone (Upper)",
		identifiedResourceName = "¿µÈ¥ÀÇÁ¶°¢",
		identifiedDescriptionName = {
			"A stone that awakens the potential of Rune Knight.",
			"Increases critical damage by 2% per each level of Dragon Training user learned.",
			"_______________________",
			"When equipped with Rune Knight Stone (Garment),",
			"reduces variable casting time by 10%.",
			"When equipped with Rune Knight Stone II (Garment),",
			"increases Hundred Spears damage by 15%.",
			"_______________________",
			"<NAVI>[Aver De Dosh]<INFO>mal_in01,23,113,0,100,0,0</INFO></NAVI>",
			"_______________________",
			"^0000CCWeight:^000000 10"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
		},
		[1000611] = {
		unidentifiedDisplayName = "Rune Knight Stone (Middle)",
		unidentifiedResourceName = "¿µÈ¥ÀÇÁ¶°¢",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Rune Knight Stone (Middle)",
		identifiedResourceName = "¿µÈ¥ÀÇÁ¶°¢",
		identifiedDescriptionName = {
			"A stone that awakens the potential of Rune Knight.",
			"Increases melee and long ranged physical damage by 1% per 2 levels of Rune Mastery user learned.",
			"_______________________",
			"When equipped with Rune Knight Stone (Garment),",
			"increases Dragon Breath and Dragon Breath - Water damage by 15%.",
			"When equipped with Rune Knight Stone II (Garment),",
			"increases Sonic Wave damage by 15%.",
			"_______________________",
			"<NAVI>[Aver De Dosh]<INFO>mal_in01,23,113,0,100,0,0</INFO></NAVI>",
			"_______________________",
			"^0000CCWeight:^000000 10"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
		},
		[1000612] = {
		unidentifiedDisplayName = "Rune Knight Stone (Lower)",
		unidentifiedResourceName = "¿µÈ¥ÀÇÁ¶°¢",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Rune Knight Stone (Lower)",
		identifiedResourceName = "¿µÈ¥ÀÇÁ¶°¢",
		identifiedDescriptionName = {
			"A stone that awakens the potential of Rune Knight.",
			"Increases Wind Cutter damage by 5% per each level of Enchant Blade user learned.",
			"_______________________",
			"When equipped with Rune Knight Stone (Garment),",
			"MaxHP/MaxSP + 10%.",
			"When equipped with Rune Knight Stone II (Garment),",
			"increases Ignition Break damage by 15%.",
			"_______________________",
			"<NAVI>[Aver De Dosh]<INFO>mal_in01,23,113,0,100,0,0</INFO></NAVI>",
			"_______________________",
			"^0000CCWeight:^000000 10"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
		},
		[310881] = {
		unidentifiedDisplayName = "Rune Knight Stone (Upper)",
		unidentifiedResourceName = "Lord_Knight_Figure",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Rune Knight Stone (Upper)",
		identifiedResourceName = "Lord_Knight_Figure",
		identifiedDescriptionName = {
			"A stone that awakens the potential of Rune Knight.",
			"Increases critical damage by 2% per each level of Dragon Training user learned.",
			"_______________________",
			"When equipped with Rune Knight Stone (Garment),",
			"reduces variable casting time by 10%.",
			"When equipped with Rune Knight Stone II (Garment),",
			"increases Hundred Spears damage by 15%.",
			"_______________________",
			"<NAVI>[Aver De Dosh]<INFO>mal_in01,23,113,0,100,0,0</INFO></NAVI>",
			"_______________________",
			"^0000CCWeight:^000000 10"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
		},
		[310882] = {
		unidentifiedDisplayName = "Rune Knight Stone (Middle)",
		unidentifiedResourceName = "Lord_Knight_Figure",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Rune Knight Stone (Middle)",
		identifiedResourceName = "Lord_Knight_Figure",
		identifiedDescriptionName = {
			"A stone that awakens the potential of Rune Knight.",
			"Increases melee and long ranged physical damage by 1% per 2 levels of Rune Mastery user learned.",
			"_______________________",
			"When equipped with Rune Knight Stone (Garment),",
			"increases Dragon Breath and Dragon Breath - Water damage by 15%.",
			"When equipped with Rune Knight Stone II (Garment),",
			"increases Sonic Wave damage by 15%.",
			"_______________________",
			"<NAVI>[Aver De Dosh]<INFO>mal_in01,23,113,0,100,0,0</INFO></NAVI>",
			"_______________________",
			"^0000CCWeight:^000000 10"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
		},
		[310883] = {
		unidentifiedDisplayName = "Rune Knight Stone (Lower)",
		unidentifiedResourceName = "Lord_Knight_Figure",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Rune Knight Stone (Lower)",
		identifiedResourceName = "Lord_Knight_Figure",
		identifiedDescriptionName = {
			"A stone that awakens the potential of Rune Knight.",
			"Increases Wind Cutter damage by 5% per each level of Enchant Blade user learned.",
			"_______________________",
			"When equipped with Rune Knight Stone (Garment),",
			"MaxHP/MaxSP + 10%.",
			"When equipped with Rune Knight Stone II (Garment),",
			"increases Ignition Break damage by 15%.",
			"_______________________",
			"<NAVI>[Aver De Dosh]<INFO>mal_in01,23,113,0,100,0,0</INFO></NAVI>",
			"_______________________",
			"^0000CCWeight:^000000 10"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
		},,
	};